create table if not exists `x_blog`(
	`id` bigint auto_increment,
	`cid` int unsigned not null default 0 comment '文章分类',
	`fid` int unsigned not null default 0 comment '来源ID,对应blog_from表,爬取时必填',
	`key` char(32) not null default '' comment '来源文章唯一号',
	`aid` int unsigned not null default 0 comment '管理员ID,默认为0',
	`title` varchar(100) not null comment '标题',
	`summary` varchar(200) not null default '' comment '文章概要',
	`cover` varchar(200) not null default '' comment '封面',
	`content` text not null,
	`tags` varchar(200) not null default '' comment '标签id,#拼接',
	`posttime` int unsigned not null default 0 comment '发布时间',
	`addtime` int unsigned not null default 0 comment '添加时间',
	`uptime` int unsigned not null default 0 comment '修改时间',
	`furl` varchar(100) not null default '' comment '来源网址',
	`status` tinyint unsigned not null default 0 comment '发布状态,1-已发布,0-未发布...',
	`sort` int unsigned not null default 0 comment '排序,越大越靠前',
	`is_ding` int unsigned not null default 0 comment '置顶',
	`view_count` int unsigned not null default 0 comment '阅读次数',
	`comment_count` int unsigned not null default 0 comment '评论次数',
	primary key(`id`),
	key cid(`cid`),
	key fid(`fid`),
	key `key`(`key`),
	key addtime(`addtime`)
)engine=InnoDB auto_increment=10000 default charset=utf8 comment='文章表';
